/sky_guard
    /models
        __init__.py
        aircraft.py
        maintenance.py
        fleet.py
        compliance.py
        user.py
    /routes
        __init__.py
        maintenance_routes.py
        fleet_routes.py
        compliance_routes.py
        user_routes.py
        dashboard_routes.py
    /services
        __init__.py
        predictive_maintenance.py
        fleet_management.py
        compliance_management.py
        notification_service.py
        data_visualization.py
    /utils
        __init__.py
        authentication.py
        logging.py
        error_handling.py
    /docs
        api_docs.md
        swagger.yaml
    app.py
    config.py
    requirements.txt
